<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dashboard_sidenav-toggler-line</name>
   <tag></tag>
   <elementGuidId>cc81852e-42b8-4cb6-98e6-3cba3087176a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='iconNavbarSidenav']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.sidenav-toggler-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#iconNavbarSidenav</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3af8f749-2cfe-494a-a12c-e8844dbf9932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidenav-toggler-line</value>
      <webElementGuid>dece44f3-4c3f-4a38-9ac6-77cecbcf871f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconNavbarSidenav&quot;)/div[@class=&quot;sidenav-toggler-inner&quot;]/i[@class=&quot;sidenav-toggler-line&quot;]</value>
      <webElementGuid>b2fbfbfc-0e81-4bd5-b5a8-fbe51571552c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='iconNavbarSidenav']/div/i</value>
      <webElementGuid>b9956c2e-74c0-4dab-b32b-2100ed79475e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>258c1390-8428-4fa2-9b61-3974487fbf2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
