<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
<<<<<<< HEAD
   <elementGuidId>66279dd0-daca-4762-b8c4-06ee0a06b8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.opacity-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbarBlur']/div/nav/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a09601f3-bc06-4917-bbcd-e23193497acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opacity-5</value>
      <webElementGuid>5fbf51aa-22c7-484d-b632-373f79e09563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/dashboard</value>
      <webElementGuid>47b38dfa-db35-4cb4-b103-c5a2a57e196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>c8792f7e-a172-4bad-8b64-639b939337df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarBlur&quot;)/div[@class=&quot;container-fluid py-1 px-2&quot;]/nav[1]/ol[@class=&quot;breadcrumb bg-transparent mb-1 pb-0 pt-1 px-0 me-sm-6 me-5&quot;]/li[@class=&quot;breadcrumb-item text-sm&quot;]/a[@class=&quot;opacity-5&quot;]</value>
      <webElementGuid>f557669f-4a0b-43a6-95bd-df931005b74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbarBlur']/div/nav/ol/li/a</value>
      <webElementGuid>1225e8fc-9722-452b-b87a-35b52adc6822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>84106ea6-35e0-4841-9ecb-a8428ebd74f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer Laboratory'])[1]/following::a[1]</value>
      <webElementGuid>21407757-64ea-4d24-b845-013ce6bcaa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer Lab'])[1]/following::a[2]</value>
      <webElementGuid>73f51d31-5947-4708-a7f9-0ee09f45b241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::a[1]</value>
      <webElementGuid>da1bd2c1-89f2-455d-b4cc-f89a9a1021b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/preceding::a[3]</value>
      <webElementGuid>0ffac563-86f7-4ea6-9ca4-e26b356ef116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>e11b31f6-0ce5-481d-8fa3-3073117fe2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/dashboard']</value>
      <webElementGuid>eb95c351-8790-407d-abe0-a0b74532ec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>5c9ad4e1-d2fe-459b-9962-e3b48d26de06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/dashboard' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>6099d3c6-648b-445f-8b5f-fc99a6fee755</webElementGuid>
=======
   <elementGuidId>861242cf-8c87-441d-b569-198d9c38d63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.opacity-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbarBlur']/div/nav/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bcb09a3-5af4-4d60-899c-c936cc32801e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opacity-5</value>
      <webElementGuid>eb1c0b4c-6140-43e4-a655-446863cdffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/dashboard</value>
      <webElementGuid>958c5fd5-2467-404d-90af-a9c5ebe28ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>5dc37ac2-d579-4297-b1f1-5e69542b908a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarBlur&quot;)/div[@class=&quot;container-fluid py-1 px-2&quot;]/nav[1]/ol[@class=&quot;breadcrumb bg-transparent mb-1 pb-0 pt-1 px-0 me-sm-6 me-5&quot;]/li[@class=&quot;breadcrumb-item text-sm&quot;]/a[@class=&quot;opacity-5&quot;]</value>
      <webElementGuid>5bf7292c-67ee-4b65-90ef-646581834977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbarBlur']/div/nav/ol/li/a</value>
      <webElementGuid>ac1ad74a-a06a-463d-8a59-d8fb28107cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>9a746ea5-13c0-4544-81d2-9b24c2a5e0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Rack'])[1]/following::a[1]</value>
      <webElementGuid>7ef5fdda-c15f-4df3-9913-780f67a37f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Student Record'])[1]/following::a[2]</value>
      <webElementGuid>62434311-8a7c-448e-8321-4e38da648818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::a[1]</value>
      <webElementGuid>99604987-1be9-4b8f-a9eb-ad1cd06172fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/preceding::a[3]</value>
      <webElementGuid>4779c082-6406-4c26-9dfd-677f14198443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>22696a3a-3096-48a9-b337-561eddd4cb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/dashboard']</value>
      <webElementGuid>13572e4b-e825-4f60-b99c-d878427a84ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>868983d5-4b9a-4297-88f7-d94b600bfafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/dashboard' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>26e7655f-426a-4ef3-b167-4cbbbb8344f4</webElementGuid>
>>>>>>> branch 'main' of https://github.com/yuweyni/pupsrc-sms.git
   </webElementXpaths>
</WebElementEntity>
