<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Room 102</name>
   <tag></tag>
   <elementGuidId>4dd84cdb-ca8f-4dd8-a37c-aa3546131551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Room 102&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f105be03-1b11-4548-9827-6792ad96d57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d61273ff-eab7-4859-8b27-2ed8ec93f228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>102</value>
      <webElementGuid>045a8f33-fd2e-4d2c-ba01-5458d633e51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary me-5 mb-3</value>
      <webElementGuid>54e05221-39b2-456b-9b69-24d6b2dd2b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Room 102</value>
      <webElementGuid>1ac5136d-6cf7-44f6-80ff-1f02afcc3afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;102&quot;)</value>
      <webElementGuid>66b62b5e-2b84-4e44-a2af-53174799252f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='102']</value>
      <webElementGuid>1501a94f-30bf-4f1f-a7d7-79de756d0de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::button[1]</value>
      <webElementGuid>9cec0643-1c82-4721-9af3-cc6a9561620c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Floor:'])[1]/following::button[2]</value>
      <webElementGuid>b035c8d8-066c-4a5f-ad84-b8d951b5f2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 104'])[1]/preceding::button[1]</value>
      <webElementGuid>f198f83e-d19f-4d30-8c58-546fb7ea08bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 106'])[1]/preceding::button[2]</value>
      <webElementGuid>4a27ade7-f1bd-4771-a814-14655f9c7623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Room 102']/parent::*</value>
      <webElementGuid>590db4d7-c940-4062-86b3-cbc03c9e5b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>97e5db77-9b06-4b52-aadd-b30331a5b703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '102' and (text() = 'Room 102' or . = 'Room 102')]</value>
      <webElementGuid>192171e0-63d8-4600-a73d-37e27e09c343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
