<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Room 109</name>
   <tag></tag>
   <elementGuidId>087aa606-5429-4f32-9158-ae336b2ed092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='109']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Room 109&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9380d61e-7a20-4090-9350-7ed00b80d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a37b1467-770d-4ec8-8a72-60af1cafdf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>109</value>
      <webElementGuid>ea3c8ecb-22d0-4cbe-9e07-d1670ee62812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary me-5 mb-3</value>
      <webElementGuid>f67a0928-f7d4-4a95-ba02-f02db7d712fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Room 109</value>
      <webElementGuid>c211bb76-c969-4332-ade6-27bb7d35b8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;109&quot;)</value>
      <webElementGuid>a780c7a3-3974-4b08-a9f2-2c8c782ed4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='109']</value>
      <webElementGuid>c5600d92-481a-4eab-9fce-5747910391ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 107'])[1]/following::button[1]</value>
      <webElementGuid>ee07ca8e-452d-481e-9991-75c2d93de550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 105'])[1]/following::button[2]</value>
      <webElementGuid>784a1cf6-6767-42a3-8394-09ab6e16258f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions Office'])[1]/preceding::button[1]</value>
      <webElementGuid>6c8e67da-8c10-4479-9a79-23755355c1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ICT Office'])[1]/preceding::button[2]</value>
      <webElementGuid>518c675f-3050-4720-bd0d-aea54a101589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Room 109']/parent::*</value>
      <webElementGuid>153db48e-a6a0-4e11-a150-e98940c0f4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[5]</value>
      <webElementGuid>38dcde86-75ef-4b39-a40a-af5f40f87547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '109' and (text() = 'Room 109' or . = 'Room 109')]</value>
      <webElementGuid>1eef7abd-65a6-4f82-914f-82f38896b0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
