<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Room 104</name>
   <tag></tag>
   <elementGuidId>65a79168-bbd2-4492-977c-a9427963667b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#104</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='104']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Room 104&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e00bd16b-c9e8-42b8-81a3-7948f416eda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bad7b374-4919-409c-898b-e5205a281040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>104</value>
      <webElementGuid>96e3c06e-678a-4079-adf8-3791865936c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary me-5 mb-3</value>
      <webElementGuid>883d9f44-eebb-41cb-a73e-d147047c7c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Room 104</value>
      <webElementGuid>836348d3-99c9-4776-96ed-0c044034ce1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;104&quot;)</value>
      <webElementGuid>599cef45-5a4b-4d19-8d96-8e21e8ef254e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='104']</value>
      <webElementGuid>1e8528c8-8e5b-4647-8c7d-1a185dbc8946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 102'])[1]/following::button[1]</value>
      <webElementGuid>e2ac79e6-a19a-43bf-b102-93f6ab480f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::button[2]</value>
      <webElementGuid>13b9de72-7894-4a93-9abc-660fe6d44a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 106'])[1]/preceding::button[1]</value>
      <webElementGuid>02c8b901-9a31-4dd4-9dcf-0688adb1b45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinic'])[1]/preceding::button[2]</value>
      <webElementGuid>61e9c3fc-5f98-4915-a6df-8f1ceb94f532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Room 104']/parent::*</value>
      <webElementGuid>ddfbe6f3-48cb-46df-bc3e-32c7ec2b9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>d28dc691-bcd5-4f3d-bead-9ce4ce0af71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '104' and (text() = 'Room 104' or . = 'Room 104')]</value>
      <webElementGuid>607d8bd1-fc4d-4d3a-818e-52212f692746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
