<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Room 107</name>
   <tag></tag>
   <elementGuidId>f7ac85c2-a301-4447-b5e5-e91932537536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#107</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='107']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Room 107&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1e796d6-37e8-449a-81e0-fe6022f15b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ee7e67b-ec9d-4b30-970d-a5f3f5c9e0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>187ffcad-b7b5-42bd-b68a-5cf3ea67cf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary me-5 mb-3</value>
      <webElementGuid>b8d68353-69a0-4daa-a9bb-9fc842da3372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Room 107</value>
      <webElementGuid>6d34b69f-bb37-4d59-9be1-614ebe294c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;107&quot;)</value>
      <webElementGuid>5f4179b8-f6cb-4004-b8bf-5b7b9c60a76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='107']</value>
      <webElementGuid>9a2fbce3-5e89-4530-9574-3d415ea4280f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 105'])[1]/following::button[1]</value>
      <webElementGuid>6181122f-94c1-4786-a48e-cc0bf7eb555a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 103'])[1]/following::button[2]</value>
      <webElementGuid>383f2b55-0ec9-458f-bdca-a94d48b0947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 109'])[1]/preceding::button[1]</value>
      <webElementGuid>49afb3c6-a550-4d80-9185-cb89880f8044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions Office'])[1]/preceding::button[2]</value>
      <webElementGuid>c549ff51-6ea2-4f09-bec1-9844561c3ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Room 107']/parent::*</value>
      <webElementGuid>9e1a43be-d0c1-4d1a-9bf3-b9c921fc5a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[4]</value>
      <webElementGuid>eb13a12f-5875-42c1-a3ef-50b015683c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '107' and (text() = 'Room 107' or . = 'Room 107')]</value>
      <webElementGuid>e8efd860-684d-4029-ae12-fc00fc5b3d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
