<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Room 105</name>
   <tag></tag>
   <elementGuidId>ea22c423-72e5-4656-a2e6-356c16b2e6df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#105</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='105']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Room 105&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79e28a7a-d320-4835-86cc-e178106726ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>267ca453-3604-40c1-88ce-22bb0349759d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>105</value>
      <webElementGuid>5f730762-a904-48a6-8071-f55b02000a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary me-5 mb-3</value>
      <webElementGuid>55b2a82a-c7c7-45ff-97d0-1f371aed173d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Room 105</value>
      <webElementGuid>ed2fe702-3f5a-4e41-a0b1-451d9fcf0d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;105&quot;)</value>
      <webElementGuid>8a14725d-e683-480a-86cf-e53cba5be931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='105']</value>
      <webElementGuid>78fbd8e7-a784-43d0-a013-d9cea4b1325c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 103'])[1]/following::button[1]</value>
      <webElementGuid>e38a56cc-cdcb-4c27-ba20-4440eccc640e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 101'])[1]/following::button[2]</value>
      <webElementGuid>49ca1f5a-7b5e-4366-905c-74d858df051f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 107'])[1]/preceding::button[1]</value>
      <webElementGuid>745ae4bd-dacf-4cb8-b804-862dd6b05917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 109'])[1]/preceding::button[2]</value>
      <webElementGuid>7366cd9d-d993-46d6-856e-c71e851fb9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Room 105']/parent::*</value>
      <webElementGuid>879c4e2a-5221-43b0-914a-1fc3d52d2cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[3]</value>
      <webElementGuid>12a95427-591e-473c-b1c1-6572563f3209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '105' and (text() = 'Room 105' or . = 'Room 105')]</value>
      <webElementGuid>da4f1646-2b17-4cb3-a903-1fccc603b6cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
