<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard_sidenav-toggler-inner</name>
   <tag></tag>
   <elementGuidId>e0f7a94a-14d0-4e46-9385-5d9e02ac1296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='iconNavbarSidenav']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sidenav-toggler-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#iconNavbarSidenav</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b76696d-98b5-488f-911c-1189403c23b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidenav-toggler-inner</value>
      <webElementGuid>73558023-71b9-4f9d-abdb-d82016499e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconNavbarSidenav&quot;)/div[@class=&quot;sidenav-toggler-inner&quot;]</value>
      <webElementGuid>baef0725-6310-4bb1-94a6-36299330aa7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='iconNavbarSidenav']/div</value>
      <webElementGuid>80bf1f7f-ff81-49e9-ab48-83d670e59b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::div[2]</value>
      <webElementGuid>46152c04-0946-4ea1-b948-a5122a39cdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>613c5465-c8d0-4a5f-bd9e-09e9d370781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/preceding::div[2]</value>
      <webElementGuid>0cfe65ac-e2e9-4d35-89f3-4cd307f43e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Settings'])[1]/preceding::div[5]</value>
      <webElementGuid>076be686-46c4-4c78-a317-fba4e81cdb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>dcea8396-9b7e-4e71-8b9b-2b070af1585e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
