<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__toggle-icon</name>
   <tag></tag>
   <elementGuidId>5e797560-36f9-4170-83ad-3896386cd3dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggle-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='toggle-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toggle-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c1ea09c5-a8db-4184-a8ae-87537ee5e838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash</value>
      <webElementGuid>618e7ed7-7d3e-46ff-a775-243573150d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-icon</value>
      <webElementGuid>0a50c938-da42-4eed-8f55-fb0c35f942e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4fbd7b7-8f36-4101-a89b-3c13f427f8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-icon&quot;)</value>
      <webElementGuid>9e451ede-4cb7-4307-b872-5176b8d295d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='toggle-icon']</value>
      <webElementGuid>a592f35d-15ab-4c10-aa5c-bfa9c69b2082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div[2]/div/span/i</value>
      <webElementGuid>7e66ab14-dc11-487d-b71f-0ace3c75b394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>435896ec-c0b7-4b03-8391-57e3c4c53b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'toggle-icon']</value>
      <webElementGuid>02697acf-f121-4cc2-8070-334cdd96e27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
