<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pulse_rate</name>
   <tag></tag>
   <elementGuidId>a4d19614-7894-4f00-ab12-b837e1580a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulse_rate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pulse_rate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Pulse Rate |bpm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22161525-9216-4531-9250-bc29db435703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40259f21-c490-484b-b406-cda51c24c916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0bb353b2-6145-4acc-baba-76936539847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pulse_rate</value>
      <webElementGuid>22008676-9108-4fef-acf7-61cbd78b5db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulse_rate</value>
      <webElementGuid>b8bafb79-98a6-46bf-a081-8b69297069f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9189353a-64ca-44f8-9ae1-4ecf45138e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pulse Rate |bpm</value>
      <webElementGuid>7c5407f7-4293-4d2f-8c02-6810c8aff728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulse_rate&quot;)</value>
      <webElementGuid>61e42408-c21d-4583-a5bc-e799d1ca08a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pulse_rate']</value>
      <webElementGuid>c88b8bec-ea7c-4d19-a8c9-31df4bdb507c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/input</value>
      <webElementGuid>22d88997-9ef2-4a28-996c-084ccce95daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pulse_rate' and @id = 'pulse_rate' and @placeholder = 'Enter Pulse Rate |bpm']</value>
      <webElementGuid>e04c9fd4-b194-4816-9564-70909d06d4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
