<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__blood_pressure</name>
   <tag></tag>
   <elementGuidId>3fdb299c-0137-46f0-b5bd-47b704fff9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#blood_pressure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='blood_pressure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Blood Pressure |mmHg&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93a674b4-e421-4782-9b45-b706cac9bcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7547334-0c1d-427b-8e0b-18fb7265986f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8f143fba-be9d-4b31-bfe4-2f466fb59093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blood_pressure</value>
      <webElementGuid>ef4362de-5620-4d70-ae6b-a36a20a7bfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blood_pressure</value>
      <webElementGuid>5a8b867d-6511-49a4-995c-ea62d7655578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>50c4c5fb-cb32-44e7-a371-3bae24289ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Blood Pressure |mmHg</value>
      <webElementGuid>065ce451-dae7-459e-868d-193362da49b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blood_pressure&quot;)</value>
      <webElementGuid>7249947c-db10-4fd2-88d2-26efd38724df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='blood_pressure']</value>
      <webElementGuid>40efb071-e2ba-4fa4-8a11-191846c5f2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>0cfdea9a-c16c-433d-bb86-a67c3a58a6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'blood_pressure' and @id = 'blood_pressure' and @placeholder = 'Enter Blood Pressure |mmHg']</value>
      <webElementGuid>44d0f4fa-e786-4215-9585-0f6dbb5eb7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
