<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__physical_assessment</name>
   <tag></tag>
   <elementGuidId>1ddc9d5d-0306-4ade-9501-63a5fdbd81bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#physical_assessment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='physical_assessment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Physical Assessment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a0e8540-5878-4598-a6d3-39b81332776d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f107c68-d641-4154-ae3d-5b25201b52b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ba72028a-d90b-411b-a91c-230078fdd100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>physical_assessment</value>
      <webElementGuid>e3b86816-b7e4-44a3-a47e-53108648b99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>physical_assessment</value>
      <webElementGuid>dc31348b-515d-4903-a842-4dcef4614b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Physical Assessment</value>
      <webElementGuid>26caf9d5-25b6-459b-9d30-64007b8ddb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ea9614a2-f419-4458-9b5a-e1a19a7dc04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;physical_assessment&quot;)</value>
      <webElementGuid>090ea100-9d54-4ea4-b721-8acfe78b0168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='physical_assessment']</value>
      <webElementGuid>8f8364e2-67e2-46f3-a829-93a553188631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>1fa04c0a-6f99-4b79-bff8-267e4d9b8270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'physical_assessment' and @id = 'physical_assessment' and @placeholder = 'Enter Physical Assessment']</value>
      <webElementGuid>12983cd5-e9a7-456b-9524-c7715db1e9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
