<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__medical_history</name>
   <tag></tag>
   <elementGuidId>658e5c20-1316-4736-8846-cedaeb244771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medical_history</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='medical_history']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Medical History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29c4de80-9bea-4706-aab4-5c6ea2b073dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18354e9f-8384-43ab-83f0-2469b1207fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4a448278-ffef-486d-8bd1-d1bdfaef5e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>medical_history</value>
      <webElementGuid>c103397f-ce2a-4ef8-92d5-7ab9a2c8b492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medical_history</value>
      <webElementGuid>ea86f718-6620-4fad-92ab-f0d383e32eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Medical History</value>
      <webElementGuid>1044733b-23b5-41a8-b074-142ecaeaaea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>226deee8-054d-4f7e-a81b-91b4e9547a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medical_history&quot;)</value>
      <webElementGuid>bd5fe814-aa58-4006-ad1f-5ff39fa2913f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='medical_history']</value>
      <webElementGuid>5ed1ad0f-05f6-4cbe-b948-ea9f6ee2b129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>506d3efb-3a84-4948-aafb-6166f3b9f3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'medical_history' and @id = 'medical_history' and @placeholder = 'Enter Medical History']</value>
      <webElementGuid>e55046cf-10ee-4f9a-adf1-bf2527de1135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
