<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__respiration</name>
   <tag></tag>
   <elementGuidId>1be296f8-b6f2-49e2-b791-89474fb8efa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#respiration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='respiration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Respiration Rate |bpm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8c5ebd8-27d1-4818-83b7-74b49a774a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66eba026-6da5-4f11-81bd-af1bd16e6a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>821c784e-7197-4d07-8302-52ee0f5c00c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>respiration</value>
      <webElementGuid>b5ab515d-0995-476b-a55e-b1c58271f5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>respiration</value>
      <webElementGuid>73f689be-50d9-48cd-8efe-34c02c8c5d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fb95d134-ccbc-4a5d-868c-ad85188aca0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Respiration Rate |bpm</value>
      <webElementGuid>3ba42b96-ac87-4faf-8a26-4cc0fd825d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;respiration&quot;)</value>
      <webElementGuid>9632d3b7-f65f-4d31-8a80-5e03dba9a611</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='respiration']</value>
      <webElementGuid>f41492d9-5111-43d0-b32d-e9ca281a9029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/input</value>
      <webElementGuid>95710310-73f9-4f15-a130-584dd7de4bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'respiration' and @id = 'respiration' and @placeholder = 'Enter Respiration Rate |bpm']</value>
      <webElementGuid>790b4d96-ca2d-47d8-9c27-53e883dee152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
