<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pup_id</name>
   <tag></tag>
   <elementGuidId>0bceca50-b170-4e96-b9c7-2a3b0d362c86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pup_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pup_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Student No.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>664cd96c-22b8-452a-bcbf-1e85513a35da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8f2458d-da05-46c2-867e-5cdd63f8448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07528a64-6701-4262-b7ee-e83b5efc503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pup_id</value>
      <webElementGuid>c836a4ff-da13-4498-b3c6-7f5d2dadf7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pup_id</value>
      <webElementGuid>6f11e4b7-b399-4eef-97b6-00f928ee1f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>0e149769-b271-4ef2-994a-e6835c5bfba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Student No.</value>
      <webElementGuid>dd0f2368-5e89-4f7f-8cc0-8e9a4184ecee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pup_id&quot;)</value>
      <webElementGuid>2ce39694-c7a6-4696-8bd8-c67d8bf906d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pup_id']</value>
      <webElementGuid>45c05930-0565-47a1-86d0-cc86b3c395bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7b4f2329-0788-4cd1-9448-0cc35c8876ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pup_id' and @id = 'pup_id' and @placeholder = 'Enter Student No.']</value>
      <webElementGuid>bb6ff7b5-c424-46e8-9c62-714b1e87154d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
