<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Extension</name>
   <tag></tag>
   <elementGuidId>422d6842-491b-489a-ae87-e2cd41cdbe3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidenav-collapse-main']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd64d2f9-e9b0-417f-8472-14ce0f8a707b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link position-relative ms-0 ps-2 py-2 </value>
      <webElementGuid>e24ede79-9a30-4755-b92f-598105bac571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/extension</value>
      <webElementGuid>fa7edc6c-5d32-48e9-8db6-38d2045b82ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Extension
                    </value>
      <webElementGuid>deb5906f-d960-40e3-bf74-d3adf3ba8212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidenav-collapse-main&quot;)/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item border-start my-0 pt-2&quot;]/a[@class=&quot;nav-link position-relative ms-0 ps-2 py-2&quot;]</value>
      <webElementGuid>7d23bb1d-8746-4a70-8647-7d60a1154f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidenav-collapse-main']/ul/li[3]/a</value>
      <webElementGuid>ded99ff6-6f18-428a-bae3-462032b9fd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research'])[1]/following::a[1]</value>
      <webElementGuid>b5f7d8dd-9aa9-4df9-9c42-5c7c6ad2bbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research and Extension'])[1]/following::a[2]</value>
      <webElementGuid>3e59ce8a-daed-4937-8b56-550c524282b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>018c065e-2e33-4cc2-8105-0367f5dede28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/extension']</value>
      <webElementGuid>505677ba-6fb6-4bc6-aeeb-2a1732fec4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>5025510d-94da-40b0-b587-048922ef7dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/extension' and (text() = '
                        Extension
                    ' or . = '
                        Extension
                    ')]</value>
      <webElementGuid>eb474274-eb9e-4dfe-a452-0d8753dc0fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
