<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard_sidenav-toggler-inner</name>
   <tag></tag>
   <elementGuidId>6be8188d-4c19-4a63-842a-5bec9cb1dee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sidenav-toggler-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='iconNavbarSidenav']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ed0b70a-adbf-4d98-9dc3-7181c5ee80f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidenav-toggler-inner</value>
      <webElementGuid>21dee8dc-d69f-4a91-a967-08102055e269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconNavbarSidenav&quot;)/div[@class=&quot;sidenav-toggler-inner&quot;]</value>
      <webElementGuid>8f117f0a-f948-4e01-aad7-d30212384e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='iconNavbarSidenav']/div</value>
      <webElementGuid>de981030-b739-4fed-9afd-6bd1db3aaca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::div[2]</value>
      <webElementGuid>e436c55b-23d1-43bb-8704-f4fa8880151a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>596cc6a9-e01b-4727-82b3-eed17f4de9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/preceding::div[2]</value>
      <webElementGuid>830ff4d5-17a0-48fd-b4f1-b54f030f26d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Settings'])[1]/preceding::div[5]</value>
      <webElementGuid>6d2183b7-643b-41bc-a178-07466746e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>5e29102d-98bf-4353-ae20-ae5ac0d6f2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
