<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Research</name>
   <tag></tag>
   <elementGuidId>1a2ae6cb-4f34-44eb-8588-37b5863bc140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.position-relative.ms-0.ps-2.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidenav-collapse-main']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a8c0994-ceb7-48f0-ac2d-28d3fb17115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link position-relative ms-0 ps-2 py-2 </value>
      <webElementGuid>9d337f56-2c36-447d-b401-8afbf18a81d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/research</value>
      <webElementGuid>68f4a015-bf4d-4fa2-8b3a-0ed7c0b3f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Research
                    </value>
      <webElementGuid>9778f36b-5d12-4663-bc61-675b262ca896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidenav-collapse-main&quot;)/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item border-start my-0 pt-2&quot;]/a[@class=&quot;nav-link position-relative ms-0 ps-2 py-2&quot;]</value>
      <webElementGuid>d99676d1-9cb7-4903-bfa5-6afeb0d5dd80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidenav-collapse-main']/ul/li[2]/a</value>
      <webElementGuid>f5b9a43b-7615-4916-905f-47b5878dbad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research and Extension'])[1]/following::a[1]</value>
      <webElementGuid>c911608e-7950-4c15-8bf5-b2d73d0fb797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUPSRC - SMS'])[1]/following::a[1]</value>
      <webElementGuid>ca9ab159-5b5e-406e-8f53-a4ffec628401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension'])[1]/preceding::a[1]</value>
      <webElementGuid>f3d289ba-0748-430c-b0b9-55552766cf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/research']</value>
      <webElementGuid>64cd4f83-3652-46b4-929a-af5c575edc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>c5dbe08e-f5c3-488c-94be-0fe9f9ce6cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/research' and (text() = '
                        Research
                    ' or . = '
                        Research
                    ')]</value>
      <webElementGuid>588f17de-264d-4fb1-a41a-a9ba8e760108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
