<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dashboard_sidenav-toggler-line</name>
   <tag></tag>
   <elementGuidId>1f719ef7-7c46-470a-a996-20c5cb733454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.sidenav-toggler-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='iconNavbarSidenav']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5a18f2bf-55b1-41aa-acb0-d8f1ee636367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidenav-toggler-line</value>
      <webElementGuid>222619f9-932e-4ac8-878c-68246effab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconNavbarSidenav&quot;)/div[@class=&quot;sidenav-toggler-inner&quot;]/i[@class=&quot;sidenav-toggler-line&quot;]</value>
      <webElementGuid>7ac0f1b7-afa5-4315-9882-322d8bd5e22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='iconNavbarSidenav']/div/i</value>
      <webElementGuid>ab023b0e-c9d2-41ac-8247-491499e3e304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>af230415-4c87-477b-9bea-7bd1d40e782f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
