<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>29d3f53d-bc91-4b81-9158-5c6a052933ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > a.dropdown-item.item > div.d-flex.flex-column.justify-content-center.px-4 > div.row > div.col > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdown-card']/div/form/a/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c253797-7a2c-4b0d-966b-df1441c93d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>773cbd63-df58-4563-97ac-4ac6c87d9c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-card&quot;)/div[1]/form[1]/a[@class=&quot;dropdown-item item&quot;]/div[@class=&quot;d-flex flex-column justify-content-center px-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/span[1]</value>
      <webElementGuid>509fe7dc-1cba-4d54-aaa6-f8ab74a61012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-card']/div/form/a/div/div/div/span</value>
      <webElementGuid>3c3bbad2-5a4c-4182-9187-ad87ed622135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Settings'])[1]/following::span[1]</value>
      <webElementGuid>1c200ac0-41ce-4eb6-b002-8527c7483761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/following::span[2]</value>
      <webElementGuid>e5a4f152-f233-4064-964b-c3725d7483f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Record'])[1]/preceding::span[1]</value>
      <webElementGuid>6f00821e-067a-4d6a-b659-febe418ff73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>be36361a-f1f5-4493-8479-8a7551303293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a/div/div/div/span</value>
      <webElementGuid>931d5ec3-74be-42c3-a0d7-98c2f673d8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>c8b97ff1-a6a9-4384-a387-8ac2b8ab9fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
