<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__toggle-icon</name>
   <tag></tag>
   <elementGuidId>282dad0c-ff29-43d7-a6a7-48afa0a5c3c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggle-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='toggle-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toggle-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4d67e86-d23b-47eb-a1c2-11a137e99e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash</value>
      <webElementGuid>80a7fd4c-0bfb-458e-8030-e6f6b04e1d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-icon</value>
      <webElementGuid>7a29b264-dce2-4f9e-99ee-ccfce5d3de1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bce5d9fe-d1c8-4107-ba89-7bc77eba9d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-icon&quot;)</value>
      <webElementGuid>26903e22-0edd-40c8-ac7f-6961dc275d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='toggle-icon']</value>
      <webElementGuid>6d6fa0fc-0f3b-418c-9310-952a0bf91862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div[2]/div/span/i</value>
      <webElementGuid>5cb0462a-d9e1-4216-9ccb-5f55215dce7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>b9d6cee6-50c6-4da9-ad99-09bb51e52a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'toggle-icon']</value>
      <webElementGuid>f51eb770-ed07-4e49-9567-e33d16e7bc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
